### ISSUE TITLE
Can't join the server in mod 2.1.1 

### ISSUE THREAD

**Issue by Edel-Lilies** [nekomaster1000/Infernal-Expansion#238]
I update mod 2.1.1 from 2.0.1,then i can't join the server.But if use 2.01 can normal join server no problom.
![QQ截图20210807101625](https://user-images.githubusercontent.com/73912246/128583502-6ec664b1-0895-41b4-8515-44cd2216f6bb.png)
This is server logs:
[10:15:21] [Server thread/INFO] [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@2186e928
[10:15:21] [Server thread/INFO] [minecraft/PlayerList]: Edel_Lilies[/127.0.0.1:63368] logged in with entity id 234 at (-945.6220335497983, 65.0, 577.9524893759511)
[10:15:21] [Server thread/INFO] [minecraft/DedicatedServer]: Edel_Lilies joined the game
[10:15:21] [Server thread/WARN] [minecraft/EntityDataManager]: defineId called for: class its_meow.betteranimalsplus.common.entity.EntityFreshwaterEel from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[10:15:21] [Server thread/WARN] [minecraft/EntityDataManager]: defineId called for: class its_meow.betteranimalsplus.common.entity.EntityFreshwaterEel from class dev.itsmeow.betteranimalsplus.imdlib.entity.util.EntityTypeContainerContainable
[10:15:22] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize zmaster587.advancedRocketry.command.StarArgument@58b564e6 (class zmaster587.advancedRocketry.command.StarArgument) - will not be sent to client!
[10:15:22] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize zmaster587.advancedRocketry.command.ReflectionArgument@70af7cd (class zmaster587.advancedRocketry.command.ReflectionArgument) - will not be sent to client!
[10:15:22] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize zmaster587.advancedRocketry.command.ReflectionArgument@5f22814f (class zmaster587.advancedRocketry.command.ReflectionArgument) - will not be sent to client!
[10:15:22] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize greekfantasy.deity.DeityArgument@24428941 (class greekfantasy.deity.DeityArgument) - will not be sent to client!
[10:15:22] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize greekfantasy.deity.DeityArgument@665a5e6c (class greekfantasy.deity.DeityArgument) - will not be sent to client!
[10:15:22] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize greekfantasy.deity.DeityArgument@24b982ed (class greekfantasy.deity.DeityArgument) - will not be sent to client!
[10:15:22] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize greekfantasy.deity.DeityArgument@1713fba (class greekfantasy.deity.DeityArgument) - will not be sent to client!
[10:15:22] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize zmaster587.advancedRocketry.command.ReflectionArgument@13679f0e (class zmaster587.advancedRocketry.command.ReflectionArgument) - will not be sent to client!
[10:15:22] [Netty Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize zmaster587.advancedRocketry.command.ReflectionArgument@531a9b90 (class zmaster587.advancedRocketry.command.ReflectionArgument) - will not be sent to client!
[10:15:22] [Server thread/WARN] [minecraft/EntityDataManager]: defineId called for: class its_meow.betteranimalsplus.common.entity.EntityLamprey from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[10:15:22] [Server thread/WARN] [minecraft/EntityDataManager]: defineId called for: class its_meow.betteranimalsplus.common.entity.EntityLamprey from class dev.itsmeow.betteranimalsplus.imdlib.entity.util.EntityTypeContainerContainable
[10:15:22] [Server thread/WARN] [minecraft/EntityDataManager]: defineId called for: class its_meow.betteranimalsplus.common.entity.EntityCoyote from class dev.itsmeow.betteranimalsplus.imdlib.entity.EntityTypeContainer
[10:15:23] [Server thread/INFO] [structurize/]: New Server UUID 9bce12a4-69fb-46bf-b5a1-ec909122bafd
[10:15:23] [Server thread/INFO] [co.si.sh.ev.CommonEvents/]: []
[10:15:23] [Server thread/INFO] [Waila/]: Syncing config to Edel_Lilies (5fe3a1c1-4549-38dd-9caa-a0592ff2b3e8)
[10:15:23] [Quark Contributor Loading Thread/ERROR] [quark/]: Failed to load patreon information
java.net.UnknownHostException: raw.githubusercontent.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_301]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_301]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_301]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_301]
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:1.8.0_301]
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) ~[?:1.8.0_301]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_301]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_301]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_301]
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:1.8.0_301]
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:1.8.0_301]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_301]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_301]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_301]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_301]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_301]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_301]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_301]
	at java.net.URL.openStream(Unknown Source) ~[?:1.8.0_301]
	at vazkii.quark.base.handler.ContributorRewardHandler$ThreadContributorListLoader.run(ContributorRewardHandler.java:144) [quark:r2.4-316]
[10:15:23] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2331ms or 46 ticks behind
[10:15:23] [Server thread/WARN] [minecraft/EntityType]: Skipping Entity with id 
[10:15:23] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: Edel_Lilies lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Modders must implement Ingredient.getSerializer in their custom Ingredients: org.infernalstudios.infernalexp.init.IEBrewingRecipes$IngredientWrapper@274081d7
[10:15:23] [Server thread/INFO] [minecraft/DedicatedServer]: Edel_Lilies left the game
[10:15:23] [Server thread/WARN] [minecraft/EntityType]: Skipping Entity with id

**Comment by LudoCrypt** [comment]
Is the server also using 2.1.1?

**Comment by Edel-Lilies** [comment]
Yes,they're also using 2.1.1. My clinet and server also is Forge 36.2.2.
It is my modlist [modlist.txt](https://github.com/infernalexp/Infernal-Expansion/files/6948440/modlist.txt)

**Comment by LudoCrypt** [comment]
ill look into this

**Comment by SwanX1** [comment]
fixed in 46f1b99d5bf6ac55062134914db70367e360cd73
