### ISSUE TITLE
crossroads incompatibility on a server

### ISSUE THREAD

**Issue by koostcrashed** [nekomaster1000/Infernal-Expansion#267]
**Describe the Bug:**
a server with these mods(forge version 1.16.5-36.2.0)
![image](https://user-images.githubusercontent.com/12761103/130334841-42e6991b-678f-4ff9-9f75-76ecb4873ec2.png)
does not boot (it also does not generate a crashlog)

I asked the Crossroads developer: he had an idea that it is caused due mixins (i am not quite sure what that entails)

**Comment by SwanX1** [comment]
please provide a log

**Comment by koostcrashed** [comment]
[21Aug2021 21:57:29.013] ain/INFO] ixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[21Aug2021 21:57:29.015] ain/INFO] ixin/]: Successfully loaded Mixin Connector [org.infernalstudios.infernalexp.mixin.MixinConnector]
[21Aug2021 21:57:29.018] ain/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[21Aug2021 21:57:35.028] odloading-worker-2/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 36.2.0, for MC 1.16.5 with MCP 20210115.111550
[21Aug2021 21:57:35.066] odloading-worker-2/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v36.2.0 Initialized
[21Aug2021 21:57:35.124] odloading-worker-4/INFO] [org.infernalstudios.infernalexp.InfernalExpansion/]: Infernal Expansion: Sound Events Registered!
[21Aug2021 21:57:35.364] odloading-worker-4/INFO] [org.infernalstudios.infernalexp.InfernalExpansion/]: Infernal Expansion: Blocks Registered!
[21Aug2021 21:57:35.365] odloading-worker-4/INFO] [org.infernalstudios.infernalexp.InfernalExpansion/]: Infernal Expansion: Items Registered!
[21Aug2021 21:57:35.368] odloading-worker-4/INFO] [org.infernalstudios.infernalexp.InfernalExpansion/]: Infernal Expansion: Effects Registered!
[21Aug2021 21:57:35.370] odloading-worker-4/INFO] [org.infernalstudios.infernalexp.InfernalExpansion/]: Infernal Expansion: Potions Registered!
[21Aug2021 21:57:35.375] odloading-worker-4/INFO] [org.infernalstudios.infernalexp.InfernalExpansion/]: Infernal Expansion: Entity Types Registered!
[21Aug2021 21:57:35.393] odloading-worker-4/INFO] [org.infernalstudios.infernalexp.InfernalExpansion/]: Infernal Expansion: Painting Types Registered!
[21Aug2021 21:57:35.403] odloading-worker-4/INFO] [org.infernalstudios.infernalexp.InfernalExpansion/]: Infernal Expansion: Tile Entity Types Registered!
[21Aug2021 21:57:35.408] odloading-worker-4/INFO] [org.infernalstudios.infernalexp.InfernalExpansion/]: Infernal Expansion: Biomes Registered!
[21Aug2021 21:57:35.417] odloading-worker-4/INFO] [org.infernalstudios.infernalexp.InfernalExpansion/]: Infernal Expansion: Loot Modifiers Registered!
[21Aug2021 21:57:35.438] odloading-worker-4/INFO] [org.infernalstudios.infernalexp.InfernalExpansion/]: Infernal Expansion: Entity Classifications Registered!
[21Aug2021 21:57:35.881] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[21Aug2021 21:57:35.881] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[21Aug2021 21:57:35.881] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[21Aug2021 21:57:35.882] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[21Aug2021 21:57:35.883] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[21Aug2021 21:57:35.883] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[21Aug2021 21:57:35.883] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[21Aug2021 21:57:35.884] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[21Aug2021 21:57:35.900] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[21Aug2021 21:57:35.901] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: Caused by: java.lang.reflect.InvocationTargetException
[21Aug2021 21:57:35.901] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21Aug2021 21:57:35.901] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21Aug2021 21:57:35.901] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21Aug2021 21:57:35.901] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[21Aug2021 21:57:35.902] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[21Aug2021 21:57:35.902] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[21Aug2021 21:57:35.902] ain/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: ... 7 more
[21Aug2021 21:57:35.902] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: Caused by: java.lang.NoClassDefFoundError: Lnet/minecraft/client/renderer/model/RenderMaterial;
[21Aug2021 21:57:35.903] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.lang.Class.getDeclaredFields0(Native Method)
[21Aug2021 21:57:35.903] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
[21Aug2021 21:57:35.903] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.lang.Class.privateGetPublicFields(Class.java:3088)
[21Aug2021 21:57:35.903] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.lang.Class.privateGetPublicFields(Class.java:3092)
[21Aug2021 21:57:35.903] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.lang.Class.privateGetPublicFields(Class.java:3098)
[21Aug2021 21:57:35.903] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.lang.Class.privateGetPublicFields(Class.java:3098)
[21Aug2021 21:57:35.904] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.lang.Class.privateGetPublicFields(Class.java:3098)
[21Aug2021 21:57:35.904] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.lang.Class.getFields(Class.java:1814)
[21Aug2021 21:57:35.904] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at net.minecraftforge.registries.ObjectHolderRegistry.scanClassForFields(ObjectHolderRegistry.java:169)
[21Aug2021 21:57:35.904] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:136)
[21Aug2021 21:57:35.904] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at net.minecraftforge.registries.ObjectHolderRegistry.lambda$findObjectHolders$5(ObjectHolderRegistry.java:107)
[21Aug2021 21:57:35.904] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[21Aug2021 21:57:35.904] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[21Aug2021 21:57:35.904] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[21Aug2021 21:57:35.905] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[21Aug2021 21:57:35.905] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[21Aug2021 21:57:35.905] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[21Aug2021 21:57:35.905] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[21Aug2021 21:57:35.905] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[21Aug2021 21:57:35.905] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[21Aug2021 21:57:35.905] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[21Aug2021 21:57:35.906] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:107)
[21Aug2021 21:57:35.906] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:197)
[21Aug2021 21:57:35.906] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44)
[21Aug2021 21:57:35.906] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: at net.minecraft.server.Main.main(Main.java:95)
[21Aug2021 21:57:35.906] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: ... 13 more
[21Aug2021 21:57:35.906] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.model.RenderMaterial
[21Aug2021 21:57:35.906] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719)
[21Aug2021 21:57:35.907] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[21Aug2021 21:57:35.907] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106)
[21Aug2021 21:57:35.907] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[21Aug2021 21:57:35.907] ain/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: ... 38 more
[21Aug2021 21:57:35.907] ain/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: Suppressed: java.lang.ClassNotFoundException
[21Aug2021 21:57:35.907] ain/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282)
[21Aug2021 21:57:35.908] ain/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[21Aug2021 21:57:35.908] ain/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[21Aug2021 21:57:35.908] ain/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: ... 39 more
>

**Comment by SwanX1** [comment]
1. Please use a service like [paste.gg](https://paste.gg/) to upload files.
2. Please provide a **full** log
3. Please use the [bug report template](https://github.com/infernalexp/Infernal-Expansion/blob/a8ce100aedc4f14f819f3a9ca1b2d185fe8367b4/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by koostcrashed** [comment]
a server with these mods(forge version 1.16.5-36.2.0)
![image](https://user-images.githubusercontent.com/12761103/130334841-42e6991b-678f-4ff9-9f75-76ecb4873ec2.png)
does not boot (it also does not generate a crashlog)

using the above list of mods on server causes it not to boot

i would expect it would

    Operating System: debian
    Mod Version: 2.2.0
    Minecraft Version: 1.16.5
    Forge Version:36.2.0
    Other mods that were running when the crash happened: ![image](https://user-images.githubusercontent.com/12761103/130334841-42e6991b-678f-4ff9-9f75-76ecb4873ec2.png)


I asked the Crossroads developer: he had an idea that it is caused due mixins (i am not quite sure what that entails)

the latest.log from the server before it shuts down
https://paste.gg/p/anonymous/c2c2226105f04b31823358dfe62a223a

(first time posting an issue here sorry)

**Comment by SwanX1** [comment]
<details>
<summary>Mentioned Users</summary>

 - @koostcrashed 
</details>

Please let me know if using this version of the mod doesn't fix your issue: [infernalstudios.org/etc/infernal-expansion-2.2.0+20210829.1.jar](https://infernalstudios.org/etc/infernal-expansion-2.2.0+20210829.1.jar)

*Issue wasn't closed due to uncertainty that this would be fixed.*

**Comment by SwanX1** [comment]
Closing this issue as it should be resolved.
