### ISSUE TITLE
Server Crash on Startup (New Map) [1.16.5] [2.3.2]

### ISSUE THREAD

**Issue by Vaex** [nekomaster1000/Infernal-Expansion#311]
**Describe the Bug:**
Crashes on first Server Startup (New World)

**How to Reproduce:**
I'm using a few other Mods but lists defenitely to Infernal-Expansion

**Expected Behavior:**
Should Startup without Crash

**Screenshots:**
-

**Version Information:**
 - Operating System: Linux
 - Mod Version: 2.3.2
 - Minecraft Version: 1.16.5
 - Forge Version: forge-1.16.5-36.2.0
 - Other mods that were running when the crash happened: -

**Additional Context:**
Crash Log

```
-- Head --
Thread: main
Stacktrace:
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211) ~[?:1.8.0_272] {}
-- MOD infernalexp --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at org.infernalstudios.infernalexp.init.IEBiomes.registerNetherBiome(IEBiomes.java:39) ~[infernalexp:2.3.2] {re:classloading}
		at org.infernalstudios.infernalexp.init.IEBiomes.<clinit>(IEBiomes.java:35) ~[infernalexp:2.3.2] {re:classloading}
		at org.infernalstudios.infernalexp.InfernalExpansion.<init>(InfernalExpansion.java:106) ~[infernalexp:2.3.2] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_272] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_272] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_272] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_272] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_272] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_272] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_272] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_272] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_272] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_272] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_272] {}

	Mod File: infernal-expansion-2.3.2.jar
	Failure message: Infernal Expansion (infernalexp) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 2.3.2
	Mod Issue URL: https://github.com/infernalexp/Infernal-Expansion/issues
	Exception message: java.util.ConcurrentModificationException
Stacktrace:
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1211) ~[?:1.8.0_272] {}
	at java.util.TreeMap$ValueIterator.next(TreeMap.java:1256) ~[?:1.8.0_272] {}
	at net.minecraftforge.common.BiomeDictionary.listSupertypes(BiomeDictionary.java:276) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.BiomeDictionary.addTypes(BiomeDictionary.java:197) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.BiomeDictionary.registerVanillaBiomes(BiomeDictionary.java:293) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.BiomeDictionary.<clinit>(BiomeDictionary.java:188) ~[forge:?] {re:classloading}
	at org.infernalstudios.infernalexp.init.IEBiomes.registerNetherBiome(IEBiomes.java:39) ~[infernalexp:2.3.2] {re:classloading}
	at org.infernalstudios.infernalexp.init.IEBiomes.<clinit>(IEBiomes.java:35) ~[infernalexp:2.3.2] {re:classloading}
	at org.infernalstudios.infernalexp.InfernalExpansion.<init>(InfernalExpansion.java:106) ~[infernalexp:2.3.2] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_272] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_272] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_272] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_272] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_272] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_272] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_272] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_272] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_272] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_272] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_272] {}


-- MOD forge --
Details:
	Mod File: forge-1.16.5-36.2.0-universal.jar
	Failure message: Forge (forge) has failed to load correctly
		java.lang.NoClassDefFoundError: Could not initialize class net.minecraftforge.common.BiomeDictionary
	Mod Version: 36.2.0
	Mod Issue URL: http://www.minecraftforge.net/
	Exception message: java.lang.NoClassDefFoundError: Could not initialize class net.minecraftforge.common.BiomeDictionary
Stacktrace:
	at net.minecraftforge.common.ForgeMod.<init>(ForgeMod.java:162) ~[forge:?] {re:classloading,re:mixin}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_272] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_272] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_272] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_272] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_272] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_272] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_272] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_272] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_272] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_272] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_272] {}
```

**Comment by ReeCodes** [comment]
ngl your forge version looks outdated

**Comment by Vaex** [comment]
> 
> 
> ngl your forge version looks outdated

Really? i'm using the Recommended Version: 1.16.5 - 36.2.0 should i update to Latest?

**Comment by Dariensg** [comment]
If you could list the other mods you were using, that would be great. It doesn't look like a Forge version issue to me, but I would also need to see the entire log, not just the end of it. If you could give both those things, that would be great! Thanks!

**Comment by Vaex** [comment]
Okay for some Reason it doesn't Crash anymore. I just downloaded the Mod again and it seems to work after multiple Startups. I'm gonna close this Issue for now but reopen if it happens again.
