### ISSUE TITLE
Crash when used with Old Guns Mod

### ISSUE THREAD

**Issue by SodiumShine** [nekomaster1000/Infernal-Expansion#376]
### Describe the Bug

When Infernal Expansion and Old Guns Mod are used together, it crashes upon firing a gun. Crash report suggests it has something to do with the glowing arrows.

### Reproduction Steps

1. Install Old Guns Mod and Infernal Expansion
2. Shoot any mob with a gun
3. Crash
...

### Expected Result

I expect the game to not crash when the two mods are used together.

### Operating System

Windows 10

### Mod Version

2.5.0

### Minecraft Version

1.18.2

### Forge Version

40.1.60

### Other Mods

Old Guns Mod
JEI

### Additional Context

```
---- Minecraft Crash Report ----
// You're mean.

Time: 7/15/22, 3:13 PM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.network.syncher.SynchedEntityData$DataItem.m_135403_()" because the return value of "net.minecraft.network.syncher.SynchedEntityData.m_135379_(net.minecraft.network.syncher.EntityDataAccessor)" is null
	at net.minecraft.network.syncher.SynchedEntityData.m_135370_(SynchedEntityData.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.projectile.AbstractArrow.getGlow(AbstractArrow.java:769) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,re:classloading,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinAbstractArrowEntity,pl:mixin:A}
	at net.minecraft.world.entity.projectile.Arrow.handler$zzc000$onArrowHitInfernalExpansion(Arrow.java:593) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,re:classloading,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinArrowEntity,pl:mixin:A}
	at net.minecraft.world.entity.projectile.Arrow.m_7761_(Arrow.java:200) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,re:classloading,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinArrowEntity,pl:mixin:A}
	at com.zach2039.oldguns.world.entity.BulletProjectile.m_5790_(BulletProjectile.java:546) ~[oldguns-1.18.2-3.3.1-27.jar%2355!/:1.18.2-3.3.1-27] {re:classloading}
	at com.zach2039.oldguns.world.entity.BulletProjectile.m_6532_(BulletProjectile.java:686) ~[oldguns-1.18.2-3.3.1-27.jar%2355!/:1.18.2-3.3.1-27] {re:classloading}
	at com.zach2039.oldguns.world.entity.BulletProjectile.m_8119_(BulletProjectile.java:905) ~[oldguns-1.18.2-3.3.1-27.jar%2355!/:1.18.2-3.3.1-27] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.network.syncher.SynchedEntityData.m_135370_(SynchedEntityData.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.projectile.AbstractArrow.getGlow(AbstractArrow.java:769) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,re:classloading,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinAbstractArrowEntity,pl:mixin:A}
	at net.minecraft.world.entity.projectile.Arrow.handler$zzc000$onArrowHitInfernalExpansion(Arrow.java:593) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,re:classloading,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinArrowEntity,pl:mixin:A}
	at net.minecraft.world.entity.projectile.Arrow.m_7761_(Arrow.java:200) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,re:classloading,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinArrowEntity,pl:mixin:A}
	at com.zach2039.oldguns.world.entity.BulletProjectile.m_5790_(BulletProjectile.java:546) ~[oldguns-1.18.2-3.3.1-27.jar%2355!/:1.18.2-3.3.1-27] {re:classloading}
	at com.zach2039.oldguns.world.entity.BulletProjectile.m_6532_(BulletProjectile.java:686) ~[oldguns-1.18.2-3.3.1-27.jar%2355!/:1.18.2-3.3.1-27] {re:classloading}
	at com.zach2039.oldguns.world.entity.BulletProjectile.m_8119_(BulletProjectile.java:905) ~[oldguns-1.18.2-3.3.1-27.jar%2355!/:1.18.2-3.3.1-27] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: oldguns:bullet_projectile (com.zach2039.oldguns.world.entity.BulletProjectile)
	Entity ID: 1031
	Entity Name: Projectile
	Entity's Exact location: -4.05, 79.52, 27.67
	Entity's Block location: World: (-5,79,27), Section: (at 11,15,11 in -1,4,1; chunk contains blocks -16,-64,16 to -1,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 1.21, -0.59, 2.59
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['Ming'/210, l='ServerLevel[New World]', x=-4.05, y=78.00, z=27.67]]
	Chunk stats: 2809
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,78,32), Section: (at 0,14,0 in 0,4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1481 game time, 1481 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 96572 (now: false), thunder time: 17989 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 931875840 bytes (888 MiB) / 3078619136 bytes (2936 MiB) up to 9462349824 bytes (9024 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 3 2200G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 17 Stepping 0
	Microarchitecture: Zen
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e89
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1640
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22293.16
	Virtual memory used (MB): 15832.31
	Swap memory total (MB): 6000.00
	Swap memory used (MB): 909.80
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9024m -Xms256m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Ming'/210, l='ServerLevel[New World]', x=-4.05, y=78.00, z=27.67]]
	Data Packs: vanilla, mod:forge, mod:patchouli (incompatible), mod:infernalexp (incompatible), mod:oldguns (incompatible), mod:jei (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18.2-40.1.60-universal.jar                |Forge                         |forge                         |40.1.60             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |DONE      |Manifest: NOSIGNATURE
		infernal-expansion-1.18.2-2.5.0.jar               |Infernal Expansion            |infernalexp                   |2.5.0               |DONE      |Manifest: NOSIGNATURE
		oldguns-1.18.2-3.3.1-27.jar                       |Old Guns Mod                  |oldguns                       |1.18.2-3.3.1-27     |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.0.209.jar                          |Just Enough Items             |jei                           |9.7.0.209           |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 6c7b0b6c-15c7-42be-a19c-97b6d3a745ff
	FML: 40.1
	Forge: net.minecraftforge:40.1.60
```

**Comment by SodiumShine** [comment]
Submitted Issue to Old Guns Mod too
https://github.com/zach2039/oldguns/issues/26

**Comment by Dariensg** [comment]
This is definitely an issue with a mixin on our end. We will look into it!

**Comment by caelwarner** [comment]
This crash was caused because of a missing `super` call in `defineSynchedData` in `BulletProjectile`. This meant that the custom data we tried to define in arrow would never actually get defined so when we later tried to retrieve that data it wouldn't exist. This has since been fixed by zach2039 by having `BulletProjectile` extend `Projectile` instead of `Arrow`.
