### ISSUE TITLE
crash before minecraft even loads

### ISSUE THREAD

**Issue by Wisychu** [nekomaster1000/Infernal-Expansion#377]
### Describe the Bug

minecraft crashes before the title screen :( i'm not entirely sure if this is this mods fault but it's the first mod name i see in the crash report

### Reproduction Steps

1. open minecraft with these mods enabled
2. congratulations! you have replicated the bug!

### Expected Result

see the title screen at least

### Operating System

Windows 10

### Mod Version

2.5.1

### Minecraft Version

1.19

### Forge Version

41.0.98

### Other Mods

Alex's Mobs
sbom_xela

AppleSkin
squeek502

AutoRegLib
Vazkii

Citadel
sbom_xela

Clumps
Jaredlll08

Controlling
Jaredlll08

Iceberg
Grend_G

Infernal Expansion
InfernalStudios

Just Enough Items (JEI)
mezz

Legendary Tooltips
Grend_G

Mouse Tweaks
YaLTeR

### Additional Context

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7/15/22, 9:51 PM
Description: Rendering overlay

java.lang.NoClassDefFoundError: net/minecraftforge/client/event/RenderNameplateEvent
	at net.minecraft.client.resources.PaintingTextureManager.handler$zbf000$getResourcesToLoad(PaintingTextureManager.java:542) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:mixin,re:classloading,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinPaintingSpriteUploader,pl:mixin:A}
	at net.minecraft.client.resources.PaintingTextureManager.m_7535_(PaintingTextureManager.java:20) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:mixin,re:classloading,pl:mixin:APP:infernal-expansion.mixins.json:client.MixinPaintingSpriteUploader,pl:mixin:A}
	at net.minecraft.client.resources.TextureAtlasHolder.m_5944_(TextureAtlasHolder.java:37) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.resources.TextureAtlasHolder.m_5944_(TextureAtlasHolder.java:13) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.event.RenderNameplateEvent
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23154!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.98.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 199945584 bytes (190 MiB) / 394264576 bytes (376 MiB) up to 9462349824 bytes (9024 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1295
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 47357.35
	Virtual memory used (MB): 25978.82
	Swap memory total (MB): 31099.52
	Swap memory used (MB): 1416.61
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9024m -Xms256m
	Launched Version: forge-41.0.98
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.95, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		MouseTweaks-forge-mc1.19-2.23.jar                 |Mouse Tweaks                  |mousetweaks                   |2.23                |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19-41.0.98-universal.jar                  |Forge                         |forge                         |41.0.98             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Iceberg-1.19-1.0.45.jar                           |Iceberg                       |iceberg                       |1.0.45              |COMMON_SET|Manifest: NOSIGNATURE
		LegendaryTooltips-1.19-1.2.5.jar                  |Legendary Tooltips            |legendarytooltips             |1.2.5               |COMMON_SET|Manifest: NOSIGNATURE
		infernal-expansion-1.19-2.5.1.jar                 |Infernal Expansion            |infernalexp                   |2.5.1               |ERROR     |Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.19-9.0.0+3.jar                     |Clumps                        |clumps                        |9.0.0+3             |COMMON_SET|Manifest: NOSIGNATURE
		Controlling-forge-1.19-10.0+3.jar                 |Controlling                   |controlling                   |10.0+3              |COMMON_SET|Manifest: NOSIGNATURE
		citadel-1.12.6-1.19.jar                           |Citadel                       |citadel                       |1.12.6              |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.19.3.jar                              |Alex's Mobs                   |alexsmobs                     |1.19.3              |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.8-54.jar                             |AutoRegLib                    |autoreglib                    |1.8-54              |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19-forge-11.0.0.222.jar                     |Just Enough Items             |jei                           |11.0.0.222          |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 62bb68c7-b5cd-4eb9-8639-959432daa802
	FML: 41.0
	Forge: net.minecraftforge:41.0.98

**Comment by Dariensg** [comment]
Forge has recently been making a lot of breaking changes. IE 1.19 is currently only compatible with Forge 41.0.63 or earlier. Downgrade your Forge. We won’t be updating until there is a stable release build as it’s not worth it to update to match the sometimes 20 or more versions of Forge in a single day.

**Comment by SwanX1** [comment]
This issue has now been fixed with version 2.5.2!
