### ISSUE TITLE
[1.18.2] Crash when starting game caused by glowstone_sparkle.json 

### ISSUE THREAD

**Issue by caniplzjustlogin4godsakesthistakesforev** [nekomaster1000/Infernal-Expansion#414]
### Describe the Bug

See attached crash report for list of installed mods and attached log below
[crash-2022-12-21_23.24.13-client.txt](https://github.com/infernalstudios/Infernal-Expansion/files/10284031/crash-2022-12-21_23.24.13-client.txt)
and 
[latest.log](https://github.com/infernalstudios/Infernal-Expansion/files/10284045/latest.log)

### Reproduction Steps

1.Have mods listed in crash report installed
2.Start game

### Expected Result

The game loading to the menu screen

### Operating System

windows 10

### Mod Version

2.5.0

### Minecraft Version

1.18.2

### Forge Version

forge-40.1.86

### Other Mods

Rubidium was installed

**Comment by caelwarner** [comment]
Does this crash happen everytime you try to launch the game? Or only occasionally?

**Comment by caniplzjustlogin4godsakesthistakesforev** [comment]
yes, when all mods are installed it happens every time, though I haven't tested that configuration in a long time

**Comment by caelwarner** [comment]
Other than Rubidium what mods did you have installed?

**Comment by MarioSMB** [comment]
This is quite a strange crash - the error pointing at Infernal Expansion is the tip of an iceberg extending all the way to a Forge error, but I suspect it may be related to Mystical World as it all appears to start with this:  
```
[21Dec2022 23:23:52.200] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: Chance data cannot be represented as list weight
	Index: 4
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4668/0x0000000800d4de18@e0ad83d
		2: net.minecraftforge.eventbus.EventBus$$Lambda$4668/0x0000000800d4de18@cac2e8
		3: net.minecraftforge.eventbus.EventBus$$Lambda$4668/0x0000000800d4de18@1d8cf83f
		4: net.minecraftforge.eventbus.EventBus$$Lambda$4668/0x0000000800d4de18@54190f05
		5: net.minecraftforge.eventbus.EventBus$$Lambda$4668/0x0000000800d4de18@c8afe8b
		6: net.minecraftforge.eventbus.EventBus$$Lambda$4668/0x0000000800d4de18@5a81a070
java.lang.IllegalStateException: Chance data cannot be represented as list weight
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.worldgen.placement.PlacementUtils.m_195364_(PlacementUtils.java:70)
	at TRANSFORMER/mysticalworld@0.4.7.28/mysticmods.mysticalworld.init.ModFeatures.lambda$static$5(ModFeatures.java:67)
	at TRANSFORMER/forge@40.1.86/net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:214)
	at TRANSFORMER/forge@40.1.86/net.minecraftforge.registries.DeferredRegister.vanillaRegister(DeferredRegister.java:465)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.2-40.1.86/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.86/net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:285)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.86/net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.86/net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:285)
	at TRANSFORMER/forge@40.1.86/net.minecraftforge.registries.GameData.postVanillaRegisterEvent(GameData.java:414)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at TRANSFORMER/forge@40.1.86/net.minecraftforge.registries.GameData.lambda$checkForRevertToVanilla$22(GameData.java:402)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.86/net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:42)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.86/net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:26)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.86/net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:202)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.86/net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.86/net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.86/net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:164)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at LAYER PLUGIN/fmlcore@1.18.2-40.1.86/net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:164)
	at TRANSFORMER/forge@40.1.86/net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:92)
	at TRANSFORMER/forge@40.1.86/net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112)
	at TRANSFORMER/forge@40.1.86/net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:92)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.<init>(Minecraft.java:459)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:169)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.86/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

[21Dec2022 23:23:52.204] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event net.minecraftforge.registries.VanillaRegisterEvent@8149b25 dispatch for modid mysticalworld
java.lang.IllegalStateException: Chance data cannot be represented as list weight
	at net.minecraft.data.worldgen.placement.PlacementUtils.m_195364_(PlacementUtils.java:70) ~[client-1.18.2-20220404.173914-srg.jar%23448!/:?]
	at mysticmods.mysticalworld.init.ModFeatures.lambda$static$5(ModFeatures.java:67) ~[mysticalworld-1.18.2-0.4.7.28.jar%23303!/:0.4.7.28]
	at net.minecraftforge.registries.DeferredRegister.lambda$register$0(DeferredRegister.java:214) ~[forge-1.18.2-40.1.86-universal.jar%23453!/:?]
	at net.minecraftforge.registries.DeferredRegister.vanillaRegister(DeferredRegister.java:465) ~[forge-1.18.2-40.1.86-universal.jar%23453!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.86.jar%23450!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:285) ~[fmlcore-1.18.2-40.1.86.jar%23449!/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:219) ~[fmlcore-1.18.2-40.1.86.jar%23449!/:?]
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:285) ~[fmlcore-1.18.2-40.1.86.jar%23449!/:?]
	at net.minecraftforge.registries.GameData.postVanillaRegisterEvent(GameData.java:414) ~[forge-1.18.2-40.1.86-universal.jar%23453!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.registries.GameData.lambda$checkForRevertToVanilla$22(GameData.java:402) ~[forge-1.18.2-40.1.86-universal.jar%23453!/:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:42) ~[fmlcore-1.18.2-40.1.86.jar%23449!/:?]
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:26) ~[fmlcore-1.18.2-40.1.86.jar%23449!/:?]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:202) ~[fmlcore-1.18.2-40.1.86.jar%23449!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.1.86.jar%23449!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187) ~[fmlcore-1.18.2-40.1.86.jar%23449!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:164) ~[fmlcore-1.18.2-40.1.86.jar%23449!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:164) ~[fmlcore-1.18.2-40.1.86.jar%23449!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:92) ~[forge-1.18.2-40.1.86-universal.jar%23453!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.18.2-40.1.86-universal.jar%23453!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:92) ~[forge-1.18.2-40.1.86-universal.jar%23453!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:459) ~[client-1.18.2-20220404.173914-srg.jar%23448!/:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%23448!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.86.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
[21Dec2022 23:23:52.226] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event LOAD_REGISTRIES, 0 errors found
```

**Comment by caelwarner** [comment]
It does look like Mystical World is responsible for this crash, causing Forge to panic. However it wouldn't explain #388. Same crash but Mystical World is not installed

**Comment by ActualLizard** [comment]
I stumbled here searching for any info on this issue as I also got it on 1.18.2. In my case it was caused by "corn delight" mod. It appears there's a incompatibility resulting in crash between Farmer's Delight 1.2.0 and corn delight <1.0.6. Version 1.0.6 fixes this crash. This would explain also #388 as there it's Farmer's Delight 1.2.0 used with corn delight 1.0.5.
Posting this here as with infernal expansion present it will likely point again to glowstone_sparkle

**Comment by Jonathing** [comment]
Duplicate of #388
