### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GauntAndreX8** [nekomaster1000/Infernal-Expansion#422]
### Describe the Bug

Just crashed when i open the game when amplified mod is installed
doesn't when i uninstall it

### Reproduction Steps

Add the amplified nether mod with it

### Expected Result

Was suppose to run smoothly but just crashed the game when started to load

### Operating System

Windows 10

### Mod Version

2.5.3

### Minecraft Version

1.19.2

### Forge Version

43.2.0

### Other Mods

```
---- Minecraft Crash Report ----
// You're mean.

Time: 2023-02-24 16:39:36
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.0-universal.jar%23264!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.2.0-universal.jar%23264!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:604) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1290) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.rehash(Object2ObjectOpenHashMap.java:1314) ~[fastutil-8.5.6.jar%23127!/:?] {}
-- MOD infernalexp --
Details:
	Mod File: /C:/Users/minee/AppData/Roaming/.minecraft/versions/1.19.2-forge-43.2.0/mods/infernal-expansion-1.19.2-2.5.3.jar
	Failure message: Infernal Expansion (infernalexp) encountered an error during the common_setup event phase
		java.lang.ArrayIndexOutOfBoundsException: Index 1024 out of bounds for length 513
	Mod Version: 2.5.1
	Mod Issue URL: https://github.com/infernalexp/Infernal-Expansion/issues
	Exception message: java.lang.ArrayIndexOutOfBoundsException: Index 1024 out of bounds for length 513
Stacktrace:
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.rehash(Object2ObjectOpenHashMap.java:1314) ~[fastutil-8.5.6.jar%23127!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.insert(Object2ObjectOpenHashMap.java:274) ~[fastutil-8.5.6.jar%23127!/:?] {}
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.put(Object2ObjectOpenHashMap.java:282) ~[fastutil-8.5.6.jar%23127!/:?] {}
	at net.minecraft.world.level.block.DispenserBlock.m_52672_(DispenserBlock.java:48) ~[client-1.19.2-20220805.130853-srg.jar%23259!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:farmersdelight.mixins.json:CuttingBoardDispenserMixin,pl:mixin:APP:moonlight-common.mixins.json:accessor.DispenserBlockAccessor,pl:mixin:A}
	at org.infernalstudios.infernalexp.InfernalExpansion.commonSetup(InfernalExpansion.java:148) ~[infernal-expansion-1.19.2-2.5.3.jar%23239!/:2.5.1] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.2.0.jar%23261!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.2.0.jar%23260!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 693444728 bytes (661 MiB) / 1207959552 bytes (1152 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x8a56
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2115
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 10686.98
	Virtual memory used (MB): 8743.07
	Swap memory total (MB): 2713.50
	Swap memory used (MB): 638.16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.19.2_HD_U_H9
	OptiFine Build: 20220820-230904
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 - Build 31.0.101.2115
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 8
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		wandering-bags-1.19.2-2.0.3.jar                   |Wandering Bags                |wandering_bags                |2.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		netherportalfix-forge-1.19-10.0.0.jar             |NetherPortalFix               |netherportalfix               |10.0.0              |SIDED_SETU|Manifest: NOSIGNATURE
		infernal-expansion-1.19.2-2.5.3.jar               |Infernal Expansion            |infernalexp                   |2.5.1               |ERROR     |Manifest: NOSIGNATURE
		spiderstpo-1.19.2-2.0.4.jar                       |Nyf's Spiders 2.0             |spiderstpo                    |2.0.4               |SIDED_SETU|Manifest: NOSIGNATURE
		treeharvester-1.19.2-7.2.jar                      |Tree Harvester                |treeharvester                 |7.2                 |SIDED_SETU|Manifest: NOSIGNATURE
		the-conjurer-1.19.2-1.1.5.jar                     |The Conjurer                  |conjurer_illager              |1.1.5               |SIDED_SETU|Manifest: NOSIGNATURE
		goblintraders-1.8.0-1.19.2.jar                    |Goblin Traders                |goblintraders                 |1.8.0               |SIDED_SETU|Manifest: NOSIGNATURE
		soundphysics-forge-1.19.2-1.0.18.jar              |Sound Physics Remastered      |sound_physics_remastered      |1.19.2-1.0.18       |SIDED_SETU|Manifest: NOSIGNATURE
		Structory-1.19-1.2.jar                            |Structory                     |structory                     |1.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		citadel-2.1.1-1.19.jar                            |Citadel                       |citadel                       |2.1.1               |SIDED_SETU|Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |SIDED_SETU|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.2.17.jar                |Bookshelf                     |bookshelf                     |16.2.17             |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		takesapillage-1.0.3-1.19.2.jar                    |It Takes A Pillage            |takesapillage                 |1.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		BiomeParticleWeather-v4.0.0-1.19-Forge.jar        |Biome Particle Weather        |impactfulweather              |4.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		balm-4.5.3.jar                                    |Balm                          |balm                          |4.5.3               |SIDED_SETU|Manifest: NOSIGNATURE
		FpsReducer2-forge-1.19.2-2.1.jar                  |FPS Reducer                   |fpsreducer                    |1.19.2-2.1          |SIDED_SETU|Manifest: NOSIGNATURE
		ShieldExpansion-1.19.2-1.1.4.jar                  |Shield Expansion              |shieldexp                     |1.1.4               |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.19.2-43.2.0-universal.jar                 |Forge                         |forge                         |43.2.0              |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		iwannaskate-1.0.1.jar                             |I Wanna Skate                 |iwannaskate                   |1.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		structure_gel-1.19.2-2.7.1.jar                    |Structure Gel API             |structure_gel                 |2.7.1               |SIDED_SETU|Manifest: NOSIGNATURE
		illager_additions-1.19-0.0.2-alpha.jar            |Illager Additions             |illager_additions             |1.19-0.0.2-alpha    |SIDED_SETU|Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |SIDED_SETU|Manifest: NOSIGNATURE
		culturaldelights-1.19.2-0.15.1.jar                |Cultural Delights             |culturaldelights              |1.19.2-0.15.1       |SIDED_SETU|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar  |EnchantmentDescriptions       |enchdesc                      |13.0.14             |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.19.2-2.0.1.136.jar           |TerraBlender                  |terrablender                  |2.0.1.136           |SIDED_SETU|Manifest: NOSIGNATURE
		moonlight-1.19.2-2.2.2-forge.jar                  |Moonlight Library             |moonlight                     |1.19.2-2.2.2        |SIDED_SETU|Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.2.13_mc1.19.2.jar          |Ambient Sounds                |ambientsounds                 |5.2.13              |SIDED_SETU|Manifest: NOSIGNATURE
		gardens-of-the-dead-1.19.2-1.1.0.jar              |Gardens of the Dead           |gardens_of_the_dead           |1.19.2-1.1.0        |SIDED_SETU|Manifest: NOSIGNATURE
		collectorsreap-1.19-1.2.jar                       |Collector's Reap              |collectorsreap                |1.2                 |SIDED_SETU|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.9.3_mc1.19.2.jar            |CreativeCore                  |creativecore                  |2.9.3               |SIDED_SETU|Manifest: NOSIGNATURE
		Amplified_Nether_v1.2.jar                         |Amplified Nether              |amplified_nether              |0.0NONE             |SIDED_SETU|Manifest: NOSIGNATURE
		NethersDelight-1.19-3.0.jar                       |Nether's Delight              |nethersdelight                |1.19-3.0            |SIDED_SETU|Manifest: NOSIGNATURE
		cloudstorage-1.3.4-1.19.2.jar                     |Cloud Storage                 |cloudstorage                  |1.3.4               |SIDED_SETU|Manifest: NOSIGNATURE
		L_Enders_Cataclysm-0.50-1.19.2.jar                |Cataclysm Mod                 |cataclysm                     |1.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		collective-1.19.2-6.48.jar                        |Collective                    |collective                    |6.48                |SIDED_SETU|Manifest: NOSIGNATURE
		entityculling-forge-1.5.2-mc1.19.1.jar            |EntityCulling                 |entityculling                 |1.5.1               |SIDED_SETU|Manifest: NOSIGNATURE
		effective_fg-1.3.4.jar                            |Effective (Forge)             |effective_fg                  |1.3.4               |SIDED_SETU|Manifest: NOSIGNATURE
		swashbucklers2.4+1.19.jar                         |HalsPirateMod                 |hpm                           |2.4                 |SIDED_SETU|Manifest: NOSIGNATURE
		ohmygoat-1.19.2-1.0.2.jar                         |Oh My Goat                    |ohmygoat                      |1.19.2-1.0.2        |SIDED_SETU|Manifest: NOSIGNATURE
		Desolation+1.1.8+1.19.2.jar                       |Desolation (Forge)            |desolation                    |1.1.8               |SIDED_SETU|Manifest: NOSIGNATURE
		abundant_atmosphere-1.19.2-1.0.2.jar              |Abundant Atmosphere           |abundant_atmosphere           |1.0.2-1.19.2        |SIDED_SETU|Manifest: NOSIGNATURE
		blueprint-1.19.2-6.1.0.jar                        |Blueprint                     |blueprint                     |6.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		savage_and_ravage-1.19.2-5.0.3.jar                |Savage & Ravage               |savage_and_ravage             |5.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		clayworks-1.19.2-2.0.0.jar                        |Clayworks                     |clayworks                     |2.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		abnormals_delight-1.19.2-4.0.1.jar                |Abnormals Delight             |abnormals_delight             |4.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		hunterillager-1.19.2-8.0.0.jar                    |Hunter Illager                |hunterillager                 |1.19.2-8.0.0        |SIDED_SETU|Manifest: NOSIGNATURE
		alexsdelight-1.4.1.jar                            |Alex's Delight                |alexsdelight                  |1.4.1               |SIDED_SETU|Manifest: NOSIGNATURE
		ferritecore-5.0.3-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.3               |SIDED_SETU|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		AI-Improvements-1.19-0.5.1.jar                    |AI-Improvements               |aiimprovements                |0.5.1               |SIDED_SETU|Manifest: NOSIGNATURE
		Enhanced_Celestials-forge-1.19.2-2.1.0.5.jar      |Enhanced Celestials           |enhancedcelestials            |2.1.0.5             |SIDED_SETU|Manifest: NOSIGNATURE
		CorgiLib-forge-1.19.2-1.0.0.24.jar                |CorgiLib                      |corgilib                      |1.0.0.24            |SIDED_SETU|Manifest: NOSIGNATURE
		bettergolem-1.19.2-2.0.0.jar                      |Better Golem                  |bettergolem                   |1.19.2-2.0.0        |SIDED_SETU|Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.39.jar                    |GeckoLib                      |geckolib3                     |3.1.39              |SIDED_SETU|Manifest: NOSIGNATURE
		creeperoverhaul-2.0.7-forge.jar                   |Creeper Overhaul              |creeperoverhaul               |2.0.7               |SIDED_SETU|Manifest: NOSIGNATURE
		End's+Phantasm+-+BETAv1.2.10.5+-+1.19.2.jar       |End's Phantasm                |phantasm                      |1.2.10.5            |SIDED_SETU|Manifest: NOSIGNATURE
		domesticationinnovation-1.6.1-1.19.2.jar          |Domestication Innovation      |domesticationinnovation       |1.6.1               |SIDED_SETU|Manifest: NOSIGNATURE
		UndeadUnleashed-1.0.1-1.19.2.jar                  |Undead Unleashed              |undead_unleashed              |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: c672db2a-88ca-47dc-aaeb-ce6b908ea8a5
	FML: 43.2
	Forge: net.minecraftforge:43.2.0
```

**Comment by Jonathing** [comment]
Still not quite sure as to why this is happening, but I've wrapped the Dispenser block registration around `event.enqueueWork()` just in case this is due to a concurrency issue.
