### ISSUE TITLE
Getting kicked out of the serv 

### ISSUE THREAD

**Issue by Jokourvite** [nekomaster1000/Infernal-Expansion#426]
### Describe the Bug

I was wandering in a dongeon from the mod stalwart dungeon (in the nether) when I got kicked by the serv
I'm playing a custom modpack with lots of mods it might be some kind of compatibility problem.
I manage the server so i'm able to provide you the error shown in the server log

I linked an old crash report because I didn't know how to provide a mod list another way

It seems to be linked with a sound but I have no idea how to fix it

### Reproduction Steps

1.Wander in a stalwart dungeon 
2.
3.
...

### Expected Result

get kicked of the server

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/127786371/224802393-a2031ed5-e13b-40c9-be4b-bb16734c7ff6.png)
```
[18:51:51] [Netty Epoll Server IO #5/ERROR] [minecraft/PacketEncoder]: Error receiving packet 96
java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.sounds.SoundEvent@363e9310' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
        at net.minecraft.network.FriendlyByteBuf.m_236818_(FriendlyByteBuf.java:125) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries.mixins.json:FriendlyByteBufMixin,pl:mixin:APP:pluto.mixins.json:shared.network.microopt.PacketByteBufMixin,pl:mixin:A}
        at net.minecraft.network.protocol.game.ClientboundSoundPacket.m_5779_(ClientboundSoundPacket.java:47) ~[server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,re:classloading}
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:45) [server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:networkstats.NettyPacketEncoderMixin,pl:mixin:A}
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) [server-1.19.2-20220805.130853-srg.jar%23453!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:networkstats.NettyPacketEncoderMixin,pl:mixin:A}
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final] {re:mixin}
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) [netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) [netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) [netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) [netty-codec-4.1.77.Final.jar%2380!/:4.1.77.Final] {re:mixin}
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) [netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-transport-4.1.77.Final.jar%2384!/:4.1.77.Final] {}
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar%2385!/:4.1.77.Final] {}
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar%2381!/:4.1.77.Final] {}
        at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
[18:51:51] [Netty Epoll Server IO #5/WARN] [co.co.Connectivity/]: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.sounds.SoundEvent@363e9310' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
```

### Operating System

Windows 11

### Mod Version

2.5.3

### Minecraft Version

1.19.3

### Forge Version

43.2.0

### Other Mods

https://mclo.gs/PbzHTuD

**Comment by SwanX1** [comment]
This most likely isn't our mod, and the log link you provided is a crash with Traveler's Backpack
